import MotionLayer from './motion-layer';

const projects=[
 {name:'Skribe',type:'Product design · AI · Legal tech',line:'Legal intelligence, made clear.',copy:'A focused workspace for navigating deposition records, key testimony, and the decisions that follow.',tone:'cream'},
 {name:'CaseCraft AI',type:'Product concept · UX · AI',line:'Turn the work into a story.',copy:'An AI-assisted builder that helps designers shape raw project notes into a clear case study.',tone:'lime'},
 {name:'AI Workspace',type:'Product exploration · AI tools',line:'A calmer way to create.',copy:'A focused exploration of conversational tools for moving from an idea to a working product.',tone:'blue'}
];
const faqs=[['What kind of work do you take on?','Product strategy, UX, interface design, design systems, and high-fidelity prototypes.'],['Can you work with an early idea?','Yes. I can frame the problem, define the first useful version, and make it testable.'],['Do you collaborate with developers?','Yes. I design with implementation in mind and stay close through handoff and iteration.'],['What tools do you use?','Figma for design and prototyping, plus AI and code tools when they help us learn faster.'],['Where are you based?','Dhaka, Bangladesh — collaborating with teams worldwide.'],['How do we start?','Send a short note about your product, its stage, and what you need help unlocking.']];
function Arrow(){return <span aria-hidden="true">↗</span>}
function Mock({tone='cream'}:{tone?:string}){return <div className={`mock ${tone}`}><header><i/><i/><i/><b>MAHIR / PRODUCT</b></header><div><aside><i/><i/><i/><i/></aside><section><small>PRODUCT WORKSPACE</small><h4>Clarity<br/>over noise.</h4><p/><p/><p/><article><em>INSIGHT</em><strong>Make the next step obvious.</strong></article></section></div></div>}
export default function Home(){return <main><MotionLayer/>
 <header className="nav"><a className="logo" href="#top">MAHIR<br/>AKASH <sup>●</sup></a><nav><a href="#work">Works</a><a href="#about">About</a><a href="#process">Process</a><a href="#contact">Contact</a></nav><a className="button" href="mailto:mahir.akash@gmail.com">Book a call <Arrow/></a></header>
 <section className="hero grid" id="top"><div className="pitch"><p>Hire your next</p><h1>Design<br/>Partner</h1><span>Product designer at Skribe. I turn complex ideas into clear, useful digital experiences.</span><a className="button" href="#work">Explore my work <Arrow/></a></div><div className="figure"><div className="halo"/><div className="head"/><div className="torso"><i/><i/><i/></div></div><div className="ticker"><span>Mahir — Product Designer — Mahir — Product Designer —&nbsp;</span></div><div className="explore"><b>RECENT EXPLORATIONS</b><div>{[...projects,...projects].map((p,i)=><article className={p.tone} key={i}><Mock tone={p.tone}/></article>)}</div></div></section>
 <section className="orange grid" id="about"><div className="inner"><p className="eyebrow">Why Mahir</p><p className="intro">When products grow complicated, momentum slows. I help teams find the essential path and make it feel natural.</p><small>That&apos;s where I come in</small><h2>I specialize in <em>product design</em><br/>for ambitious digital teams.</h2><p>From early framing to a polished, build-ready interface, I create experiences that are thoughtful, coherent, and ready to evolve.</p><div className="chips"><span>✦ Product thinking</span><span>◎ Clear systems</span><span>↗ Working prototypes</span></div><small>Currently designing at</small><div className="logos"><b>Skribe</b><span>Legal tech</span><span>AI products</span><span>Design systems</span></div></div></section>
 <section className="work grid" id="work"><div className="inner"><p className="eyebrow">Selected work</p><h2>Explore some of my<br/><em>product stories.</em></h2>{projects.map((p,i)=><article className="case" key={p.name}><div className={`visual ${p.tone}`}><Mock tone={p.tone}/><span>0{i+1}<b>{p.line}</b></span></div><div className="casecopy"><div><small>{p.type}</small><h3>{p.name}</h3><p>{p.copy}</p></div><a href="mailto:mahir.akash@gmail.com">Discuss a similar project <Arrow/></a></div></article>)}</div></section>
 <section className="offer grid"><div className="inner"><div className="banner"><small>HAVE SOMETHING COMPLEX IN MIND?</small><h2>Let&apos;s make the path<br/>forward feel obvious.</h2><a className="button" href="mailto:mahir.akash@gmail.com">Start a conversation <Arrow/></a></div><p className="eyebrow">Ways I can help</p><h2>Flexible collaboration,<br/><em>shaped around the product.</em></h2><div className="services">{[['01','Product direction','Problem framing|Experience principles|Roadmap clarity|Concept validation'],['02','Experience design','User flows|Information architecture|Interface design|Interactive prototypes'],['03','Product systems','Design systems|Responsive patterns|Developer handoff|Ongoing support']].map(x=><article key={x[0]}><small>{x[0]}</small><h3>{x[1]}</h3>{x[2].split('|').map(y=><p key={y}>○ {y}</p>)}</article>)}</div></div></section>
 <section className="process grid" id="process"><div className="inner"><p className="eyebrow">My process</p><h2>A focused path from<br/><em>question to clarity.</em></h2><div className="steps">{['Discover','Frame','Explore','Prototype','Refine','Handoff'].map((s,i)=><article key={s}><small>0{i+1}</small><b>{s}</b><span>{['Context & goals','Flows & priorities','Directions','Real interactions','Feedback loops','Support'][i]}</span></article>)}</div><div className="arrowline">↝</div></div></section>
 <section className="faq grid"><div className="inner"><p className="eyebrow">Frequently asked questions</p><h2>Here&apos;s what teams<br/><em>usually ask.</em></h2><div className="faqs">{faqs.map((f,i)=><article key={f[0]}><h3>{i+1}. {f[0]}</h3><p>{f[1]}</p></article>)}</div><div className="question"><em>Still have a question?</em><a href="mailto:mahir.akash@gmail.com">Write to Mahir <Arrow/></a></div></div></section>
 <section className="contact grid" id="contact"><div className="inner"><p>Have a <em>product idea?</em></p><h2>Let&apos;s bring it to life.</h2><span>Share the context, the challenge, and where you want to go next.</span><a className="button" href="mailto:mahir.akash@gmail.com">mahir.akash@gmail.com <Arrow/></a></div></section>
 <footer className="grid"><div className="photos">{['Product','People','Places','Ideas','Progress'].map((x,i)=><i key={x} style={{'--r':`${[-7,4,-2,6,-5][i]}deg`} as React.CSSProperties}>{x}</i>)}</div><div className="footcard"><div><span className="avatar">M</span><h2>I&apos;m Mahir.</h2><p>I care about making useful products feel ready, clear, and human.</p><small>● &nbsp; Open to meaningful collaborations</small></div><div><a href="https://github.com/mahirakash">GitHub <Arrow/></a><a href="mailto:mahir.akash@gmail.com">Email <Arrow/></a><span>Dhaka, Bangladesh<br/>Working worldwide</span></div></div><div className="copyright">© {new Date().getFullYear()} Mahir <a href="#top">Back to top ↑</a></div><strong className="mahir">mahir</strong></footer>
 </main>}
