import MotionLayer from './motion-layer';
import FloatingNav from './floating-nav';

const work=[
 {name:'Skribe',url:'https://skribe.ai',mark:'Skribe',tone:'violet',copy:'The non-stenographic alternative to court reporting—giving litigation teams the speed, tools, and control modern cases demand.',tags:'Legaltech · Depositions · AI · Litigation · Courtroom'},
 {name:'Vendidit',url:'https://vendidit.com',mark:'vendidit',tone:'pink',copy:'A modern reverse-logistics marketplace helping sellers move returned, overstocked, and resold items efficiently while giving buyers access to high-value second-chance products.',tags:'Recommerce · AI · Marketplace · Auctions · Inventory'},
 {name:'Sendwin',url:'https://send.win',mark:'Sendwin',tone:'mint',copy:'A browser-based productivity tool for managing multiple accounts on the same website within a single, completely isolated and private browser session.',tags:'MultiLogin · Isolation · Productivity · Privacy · Proxy'},
 {name:'Sootcase',url:'https://sootcase.co',mark:'sootcase',tone:'green',copy:'An itinerary-planning app that brings every trip detail—reservations, confirmations, and inspiration—into one beautiful, shareable hub.',tags:'Itinerary · Travel · Planning · Collaboration · Organizer'}
];
const services=[
 ['Product clarity','UX Strategy & Flow Design','User journeys and flows that align business goals with user needs—fast, logical, and friction-free.'],
 ['Interface that works','UI / Visual Design','Clean, modern, scalable design systems with high usability and visual polish. Built for clarity and trust.'],
 ['Real-world systems','Systems & Documentation','Component libraries, guidelines, and Figma systems that reduce friction across design and development.'],
 ['Sites that sell','WP, HubSpot & Webflow Sites','Conversion-focused marketing websites and landing pages with responsive, SEO-aware execution.'],
 ['Growth-driven design','Marketing Assets','Launch graphics and visuals that amplify product stories and drive engagement.'],
 ['Team enablement','Full-Stack Development','Production-ready implementation delivered with an engineering team, from front end through back end.']
];
function Arrow(){return <span aria-hidden="true">↗</span>}
export default function Home(){return <main><MotionLayer/>
 <section className="hero hero-editorial grid" id="top"><div className="hero-copy"><p className="hero-kicker">Your next design partner</p><h1>Clarity.<br/>Speed.<br/>Design that<br/>performs.</h1><p className="hero-summary">I&apos;m Mahir Abrar Akash, helping companies turn complex ideas into clean, conversion-focused digital experiences.</p><div className="hero-actions"><a className="button" href="#meeting">Schedule a call <Arrow/></a><a className="textlink" href="mailto:mahir.akash@gmail.com">Contact me</a></div><aside aria-label="Experience highlights"><div><b>100+</b><span>Clients served</span></div><div><b>8+</b><span>Years in UI/UX</span></div></aside></div><div className="hero-portrait"><img src="/MahirWeb-Pic.png" alt="Mahir Abrar Akash, product designer"/></div><FloatingNav/></section>
 <section className="client-section grid" aria-labelledby="clients-heading"><div className="client-inner"><p className="eyebrow">Selected collaborations</p><h2 id="clients-heading">Previously worked with</h2><div className="client-slider"><div className="client-track">{[...work,...work].map((client,index)=><a key={`${client.name}-${index}`} href={client.url} target="_blank" rel="noreferrer" aria-label={index<work.length?`Visit ${client.name}`:undefined} aria-hidden={index>=work.length} tabIndex={index>=work.length?-1:undefined}><span>{client.mark}</span><small>{client.tags.split(' · ')[0]}</small></a>)}</div></div></div></section>
 <section className="orange grid" id="about"><div className="inner"><p className="eyebrow">About me</p><p className="intro">Design is how I shape clarity into action.<br/>I don&apos;t just build screens—I build momentum.</p><small>Product Designer &amp; Growth Collaborator</small><h2>I work where <em>function, emotion,</em><br/>and conversion meet.</h2><p>I&apos;ve helped SaaS platforms, startups, and digital brands grow with smart, system-driven design. From shipping MVPs to scaling enterprise dashboards, I focus on work that moves products forward.</p><p>Today I work remotely with U.S.-based <strong>Skribe.ai</strong>, leading product design while supporting brand and growth.</p><div className="chips"><span>Figma</span><span>Notion</span><span>WordPress</span><span>Webflow</span><span>Business context</span></div></div></section>
 <section className="work grid" id="work"><div className="inner"><p className="eyebrow">Selected work</p><h2>Products shaped for<br/><em>real-world momentum.</em></h2>{work.map((p,i)=><article className="case" key={p.name}><div className={"visual "+p.tone}><div className="brandmark"><small>0{i+1}</small><strong>{p.mark}</strong><span>{p.tags}</span></div></div><div className="casecopy"><div><small>Case study · Coming soon</small><h3>{p.name}</h3><p>{p.copy}</p><span>{p.tags}</span></div><a href={p.url} target="_blank" rel="noreferrer">Visit website <Arrow/></a></div></article>)}</div></section>
 <section className="process grid" id="process"><div className="inner"><p className="eyebrow">How I work</p><h2>Vision into action.<br/><em>Action into momentum.</em></h2><div className="steps">{[['01','Discover & Define','I dig into goals, behavior, and constraints to define what needs designing—and why.'],['02','Systems Over Screens','I build scalable UI systems and thoughtful flows focused on outcomes, not pixels for their own sake.'],['03','Collaborate & Ship','I work closely with product, engineering, and growth from handoff through post-launch learning.']].map(x=><article key={x[0]}><small>{x[0]}</small><b>{x[1]}</b><span>{x[2]}</span></article>)}</div></div></section>
 <section className="offer grid" id="services"><div className="inner"><p className="eyebrow">Services I offer</p><h2>From product clarity<br/>to <em>production-ready.</em></h2><div className="services">{services.map((s,i)=><article key={s[1]}><small>0{i+1} · {s[0]}</small><h3>{s[1]}</h3><p>{s[2]}</p></article>)}</div></div></section>
 <section className="meeting grid" id="meeting"><div className="inner"><p className="eyebrow">Schedule a meeting</p><h2>Have an <em>idea, product,</em><br/>or vision to shape?</h2><p>Choose a time below and let&apos;s talk through it—clearly, directly, and without pressure.</p><iframe title="Book a meeting with Mahir" src="https://cal.com/mahirakash/15min?embed=true&theme=dark" loading="lazy" allow="payment" /></div></section>
 <footer className="site-footer grid"><div className="footer-intro"><p className="eyebrow">Have a product in motion?</p><h2>Let&apos;s make the<br/><em>next step clear.</em></h2><p>Product strategy, UX, visual systems, and build-ready collaboration for teams turning complex ideas into useful products.</p><a className="button" href="#meeting">Schedule a call <Arrow/></a></div><div className="footcard"><div className="footer-profile"><span className="avatar">M</span><h3>Mahir Abrar Akash</h3><p>Product designer &amp; growth collaborator based in Dhaka, working worldwide.</p><small><i/> Available for meaningful collaborations</small></div><div className="footer-links"><a href="https://github.com/mahirakash" target="_blank" rel="noreferrer">GitHub <Arrow/></a><a href="mailto:mahir.akash@gmail.com">Email <Arrow/></a><a href="#work">Selected work <Arrow/></a><span><b>Based in</b> Dhaka, Bangladesh<br/><b>Working with</b> teams worldwide</span></div></div><div className="copyright"><span>© {new Date().getFullYear()} Mahir Abrar Akash</span><span>Designed for clarity. Built for momentum.</span><a href="#top">Back to top ↑</a></div><strong className="mahir" aria-hidden="true">MAHIR</strong></footer>
 </main>}
